# -*- coding: utf-8 -*-
"""BDA Preprocessed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rb4K1BFMtngRoEHHsayMK9vcfb-ffF8F
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

# Load review datasets
dfr1 = pd.read_csv('rotten_tomatoes_critic_reviews.csv')
dfr2 = pd.read_csv('rotten_tomatoes_movie_reviews.csv')
# Load movie datasets
dfm1 = pd.read_csv('rotten_tomatoes_movies.csv')
dfm2 = pd.read_csv('rotten_tomatoes_movies.csv')

# Check the shape of the datasets
print(dfr1.shape)
print(dfr2.shape)
print(dfm1.shape)
print(dfm2.shape)

# Display the first row of each dataset
for i in (dfr1, dfr2, dfm1, dfm2):
    display(i.head(1))
    print(i.info())

# Install and import dependencies
!pip install pyspark nltk

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, regexp_replace, lower, udf, when
from pyspark.sql.types import StringType, ArrayType
from pyspark.ml.feature import Tokenizer, StopWordsRemover
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords

# Initialize Spark session
spark = SparkSession.builder.appName("RottenTomatoes_Preprocessing").getOrCreate()

# Load CSV files
dfr1 = spark.read.csv("/content/rotten_tomatoes_critic_reviews.csv", header=True, inferSchema=True)
dfr2 = spark.read.csv("/content/rotten_tomatoes_movie_reviews.csv", header=True, inferSchema=True)
dfm = spark.read.csv("/content/rotten_tomatoes_movies.csv", header=True, inferSchema=True)

print("Datasets loaded successfully!")

# Rename columns for consistency
dfr1 = dfr1.withColumnRenamed("rotten_tomatoes_link", "id") \
           .withColumnRenamed("critic_name", "criticName") \
           .withColumnRenamed("review_type", "reviewType") \
           .withColumnRenamed("review_score", "reviewScore") \
           .withColumnRenamed("review_date", "reviewDate") \
           .withColumnRenamed("review_content", "reviewText")

dfm = dfm.withColumnRenamed("rotten_tomatoes_link", "id") \
         .withColumnRenamed("movie_title", "movieTitle")

# Handle missing values and clean text
dfr1 = dfr1.withColumn("reviewText", when(col("reviewText").isNull(), "").otherwise(col("reviewText")))
dfm = dfm.withColumn("movieTitle", when(col("movieTitle").isNull(), "").otherwise(col("movieTitle")))

dfr1 = dfr1.withColumn("reviewText", regexp_replace(col("reviewText"), "[^a-zA-Z0-9\\s]", " "))
dfm = dfm.withColumn("movieTitle", regexp_replace(col("movieTitle"), "[^a-zA-Z0-9\\s]", " "))

dfr1 = dfr1.withColumn("reviewText", lower(col("reviewText")))
dfm = dfm.withColumn("movieTitle", lower(col("movieTitle")))

# Tokenize text
tokenizer = Tokenizer(inputCol="reviewText", outputCol="tokens")
dfr1 = tokenizer.transform(dfr1)

# Remove stopwords
remover = StopWordsRemover(inputCol="tokens", outputCol="filtered_tokens")
dfr1 = remover.transform(dfr1)

# Apply stemming and lemmatization
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def stem_lemmatize(tokens):
    if not tokens:
        return []
    processed = []
    for word in tokens:
        if word not in stop_words:
            stemmed = ps.stem(word)
            lemm = lemmatizer.lemmatize(stemmed)
            processed.append(lemm)
    return processed

stem_lemmatize_udf = udf(stem_lemmatize, ArrayType(StringType()))
dfr1 = dfr1.withColumn("clean_tokens", stem_lemmatize_udf(col("filtered_tokens")))

# Join reviews with movies
df_joined = dfr1.join(dfm, on="id", how="inner")
print(f"Joined Data Shape: {df_joined.count()} rows, {len(df_joined.columns)} columns")

# Limit dataset for memory constraints
df_sample = df_joined.limit(500000)

# Final cleanup
df_sample = df_sample.withColumn("reviewText", regexp_replace(col("reviewText"), "[,;!?]", " "))
df_sample = df_sample.withColumn("movieTitle", regexp_replace(col("movieTitle"), "[,;!?]", " "))

# Save final dataset to CSV
output_path = "/content/big_movies.csv"
df_sample.toPandas().to_csv(output_path, index=False)

print("Final cleaned dataset saved as big_movies.csv for Hadoop.")

from google.colab import files
files.download("/content/big_movies.csv")

