# -*- coding: utf-8 -*-
"""IMDb_Recommender_BDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-E01r2EgE78saWna1rDLVlqN4cI9kL5
"""

# Install libraries and authenticate
!pip install -q google-cloud-dataproc google-cloud-storage google-auth

from google.colab import auth
auth.authenticate_user()
print("Authenticated successfully.")

from google.cloud import dataproc_v1
PROJECT_ID = "movie-sentiment-recommender"
REGION = "asia-south2"
CLUSTER_NAME = "bda-cluster-demo"
BUCKET = "anjali-bda"
JOB_FILE = f"gs://{BUCKET}/bda_project.py"
print("Configured successfully.")

# Automatically create Dataproc cluster if missing
from google.api_core.exceptions import NotFound

cluster_client = dataproc_v1.ClusterControllerClient(
    client_options={"api_endpoint": f"{REGION}-dataproc.googleapis.com:443"}
)

def ensure_cluster():
    try:
        cluster_client.get_cluster(
            request={"project_id": PROJECT_ID, "region": REGION, "cluster_name": CLUSTER_NAME}
        )
        print(f"Cluster '{CLUSTER_NAME}' already exists.")
    except NotFound:
        print(f"Cluster '{CLUSTER_NAME}' not found — creating new cluster...")
        cluster_config = {
            "project_id": PROJECT_ID,
            "cluster_name": CLUSTER_NAME,
            "config": {
                "gce_cluster_config": {"zone_uri": f"{REGION}-b"},
                "master_config": {
                    "num_instances": 1,
                    "machine_type_uri": "e2-standard-2",
                    "disk_config": {"boot_disk_size_gb": 30},
                },
                "worker_config": {
                    "num_instances": 2,
                    "machine_type_uri": "e2-standard-2",
                    "disk_config": {"boot_disk_size_gb": 30},
                },
                "software_config": {
                    "image_version": "2.1-debian11",
                    "properties": {"dataproc:dataproc.allow.zero.workers": "true"},
                },
                "initialization_actions": [
                    {"executable_file": f"gs://{BUCKET}/init-actions/pip-install.sh"}
                ],
                "metadata": {
                    "PIP_PACKAGES": "nltk pandas textblob wordcloud scikit-learn tqdm fsspec==2023.10.0 gcsfs==2023.10.0"
                },
                "lifecycle_config": {"idle_delete_ttl": {"seconds": 1800}},  # 30 min idle auto-delete
            },
        }
        op = cluster_client.create_cluster(
            request={"project_id": PROJECT_ID, "region": REGION, "cluster": cluster_config}
        )
        print("Creating cluster – please wait (~3 min)…")
        op.result()
        print(f"Cluster '{CLUSTER_NAME}' created successfully!")

ensure_cluster()

# Show active Dataproc cluster details
cluster = cluster_client.get_cluster(
    request={"project_id": PROJECT_ID, "region": REGION, "cluster_name": CLUSTER_NAME}
)
print(f"\nCluster '{CLUSTER_NAME}' is ACTIVE!")
print(f"Region: {REGION}")
print(f"Master node: {cluster.config.master_config.num_instances} × {cluster.config.master_config.machine_type_uri}")
print(f"Worker nodes: {cluster.config.worker_config.num_instances} × {cluster.config.worker_config.machine_type_uri}")
print(f"\nView real-time jobs: https://console.cloud.google.com/dataproc/jobs?project={PROJECT_ID}&region={REGION}")

# List the actual VM instances belonging to this cluster
!gcloud compute instances list --filter="name:bda-cluster-demo" --project=movie-sentiment-recommender

# Submit job to Dataproc cluster
job_client = dataproc_v1.JobControllerClient(
    client_options={"api_endpoint": f"{REGION}-dataproc.googleapis.com:443"}
)
job = {
    "placement": {"cluster_name": CLUSTER_NAME},
    "pyspark_job": {"main_python_file_uri": JOB_FILE},
}
print("Submitting job to Dataproc...")
operation = job_client.submit_job_as_operation(
    request={"project_id": PROJECT_ID, "region": REGION, "job": job}
)
operation.result()
print("Job completed successfully on Dataproc cluster!")

from google.colab import auth
auth.authenticate_user()

import pandas as pd
import numpy as np
import re
import requests
from textblob import TextBlob
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load preprocessed data from Google Cloud Storage
path = "gs://anjali-bda/output/cleaned_reviews.csv"
df = pd.read_csv(path)
print(f"Loaded {len(df)} cleaned reviews from Dataproc")

# Build TF-IDF model
movie_texts = (
    df.groupby("movie_title")["clean_review"]
    .apply(lambda x: " ".join(str(t) for t in x))
    .reset_index()
)
tfidf = TfidfVectorizer(stop_words="english", max_features=5000)
tfidf_matrix = tfidf.fit_transform(movie_texts["clean_review"])
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
movie_indices = pd.Series(movie_texts.index, index=movie_texts["movie_title"])

# Take user input
movie_name = input("Enter a movie name: ").strip().lower()

# Fetch IMDb data
OMDB_API_KEY = "c74664dc"

def fetch_omdb(title):
    url = f"http://www.omdbapi.com/?t={title}&apikey={OMDB_API_KEY}"
    return requests.get(url).json()

imdb_data = fetch_omdb(movie_name)
if imdb_data.get("Response") == "True":
    print(f"\nIMDb: {imdb_data.get('Title')} ({imdb_data.get('Year')})")
    print(f"Rating: {imdb_data.get('imdbRating')}")
    print(f"Plot: {imdb_data.get('Plot')}")
else:
    print("IMDb data not found.")

# Recommend similar movies based on TF-IDF and sentiment
def normalize(title):
    return re.sub(r'[^a-z0-9]+', ' ', str(title).lower()).strip()

movie_texts["norm_title"] = movie_texts["movie_title"].apply(normalize)
normalized_input = normalize(movie_name)

matches = [
    m for m, norm in zip(movie_texts["movie_title"], movie_texts["norm_title"])
    if normalized_input in norm or norm in normalized_input
]

if not matches:
    print(f"No local reviews found for '{movie_name}'.")
else:
    target_movie = matches[0]
    print(f"Matched local title: {target_movie}")
    idx = movie_indices[target_movie]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:10]

    recs = []
    for i, sim_val in sim_scores:
        title = movie_texts.loc[i, "movie_title"]
        sent = df[df["movie_title"] == title]["normalized_sentiment"].mean()
        sent = 0 if np.isnan(sent) else sent
        blended = 0.7 * sim_val + 0.3 * sent
        recs.append((title, sim_val, sent, blended))

    rec_df = pd.DataFrame(recs, columns=["Movie", "Similarity", "Sentiment", "Rank"])
    rec_df = rec_df.sort_values("Rank", ascending=False).head(5)

    print(f"\nTop 5 Recommendations for '{movie_name}':\n")
    for _, r in rec_df.iterrows():
        print(f"{r['Movie']} | Similarity: {r['Similarity']:.3f} | Sentiment: {r['Sentiment']:.2f}")

df = pd.read_csv("gs://anjali-bda/output/cleaned_reviews.csv")

# Assuming 'normalized_sentiment' ranges from 0 to 1
positive = (df["normalized_sentiment"] >= 0.75).mean() * 100
neutral = ((df["normalized_sentiment"] >=0.45 ) & (df["normalized_sentiment"] < 0.75)).mean() * 100
negative = (df["normalized_sentiment"] < 0.45).mean() * 100

print(f"Sentiment Distribution:\nPositive: {positive:.2f}%\nNeutral: {neutral:.2f}%\nNegative: {negative:.2f}%")

# Delete Dataproc cluster when done
print(f"Deleting cluster '{CLUSTER_NAME}' to save credits...")
del_op = cluster_client.delete_cluster(
    request={"project_id": PROJECT_ID, "region": REGION, "cluster_name": CLUSTER_NAME}
)
del_op.result()
print(f"Cluster '{CLUSTER_NAME}' deleted successfully.")

