# -*- coding: utf-8 -*-
"""Sentiment_Analysis_BDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R01MH8hSeTIfgGWeh8-SeHg6gg89EaDf
"""

import pandas as pd
import numpy as np
import re
import os
import subprocess
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from textblob import TextBlob

# NLTK resources (kept as-is — required resources for tokenization/lemmatization)
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

# GCS paths
INPUT_PATH = "gs://anjali-bda/big_movies.csv"
OUTPUT_PATH = "gs://anjali-bda/output"

print("Starting Movie Sentiment Recommender pipeline...")
print(f"Reading input dataset from: {INPUT_PATH}")

# Load dataset
df = pd.read_csv(INPUT_PATH)
print(f"Loaded {len(df)} rows.")

# Basic cleaning
expected_cols = ['id', 'reviewText', 'reviewScore', 'reviewDate']
if all(c in df.columns for c in expected_cols):
    df = df[expected_cols].copy()
    df.rename(columns={
        'id': 'movie_title',
        'reviewText': 'review_content',
        'reviewScore': 'review_score',
        'reviewDate': 'review_date'
    }, inplace=True)
else:
    df = df.rename(columns={
        "movieTitle": "movie_title",
        "reviewText": "review_content"
    })

# ensure required text columns are present and of string type
df.dropna(subset=['movie_title', 'review_content'], inplace=True)
df['movie_title'] = df['movie_title'].astype(str)
df['review_content'] = df['review_content'].astype(str)

# Preprocessing
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    """Lowercase, remove non-alphanumeric characters, tokenize,
    remove stopwords, lemmatize, and return cleaned string."""
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    tokens = word_tokenize(text)
    tokens = [t for t in tokens if t.isalpha() and t not in stop_words]
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return ' '.join(tokens)

print("Cleaning reviews...")
df['clean_review'] = df['review_content'].apply(preprocess_text)

# Compute sentiment polarity
print("Calculating sentiment polarity...")
df['polarity'] = df['clean_review'].apply(lambda x: TextBlob(x).sentiment.polarity)

# Normalize polarity (0–1 scale)
# prevents division by zero when all polarities are equal
pol_min = df['polarity'].min()
pol_max = df['polarity'].max()
if pol_max - pol_min == 0:
    df['normalized_sentiment'] = 0.5  # fallback to mid-point if no variance
else:
    df['normalized_sentiment'] = (df['polarity'] - pol_min) / (pol_max - pol_min)

# Sentiment labels
def sentiment_label(score):
    if score >= 0.75:
        return "Positive"
    elif score >= 0.45:
        return "Neutral"
    else:
        return "Negative"

df['sentiment_label'] = df['normalized_sentiment'].apply(sentiment_label)

print("Sentiment normalization and labeling complete.")

# Export cleaned data for Colab
os.makedirs("/tmp/output", exist_ok=True)
out_path = "/tmp/output/cleaned_reviews.csv"
df[['movie_title', 'clean_review', 'normalized_sentiment', 'sentiment_label']].to_csv(out_path, index=False)

print("Attempting to upload cleaned dataset to GCS...")
try:
    subprocess.run(["gsutil", "cp", out_path, f"{OUTPUT_PATH}/cleaned_reviews.csv"], check=True)
    print("Exported cleaned dataset for Colab integration.")
except subprocess.CalledProcessError:
    print("Warning: Upload to GCS failed. Please re-run the gsutil copy command manually:")
    print(f"   gsutil cp {out_path} {OUTPUT_PATH}/cleaned_reviews.csv")

print("Dataproc pipeline completed successfully!")